### ISSUE TITLE
请问您的雷达是什么型号啊，谢谢大佬

### ISSUE THREAD

**Issue by GuobaPei** [dondaha/smartcar2023#1]
，看您的这个雷达效果很好又拿了奖，好奇是哪个嘿嘿嘿，是思岚a1吗？？

**Comment by dondaha** [comment]
我用的是这款（YDLIDAR X3），老实说不如别组的固态激光雷达
![image](https://github.com/user-attachments/assets/ae4fce73-4d1f-4e22-96a7-508f3ed9a7be)

**Comment by GuobaPei** [comment]
hhhhh，谢谢大佬啦
